{{- if and .Values.orchestrator.enabled .Values.orchestrator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.orchestrator.serviceAccount.name | default "cloudscan-orchestrator" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudscan.labels" . | nindent 4 }}
  {{- with .Values.orchestrator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}