{{- if and .Values.orchestrator.enabled .Values.orchestrator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cloudscan.fullname" . }}-orchestrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudscan.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudscan.fullname" . }}-orchestrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudscan.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cloudscan.fullname" . }}-orchestrator
subjects:
- kind: ServiceAccount
  name: {{ .Values.orchestrator.serviceAccount.name | default "cloudscan-orchestrator" }}
  namespace: {{ .Release.Namespace }}
{{- end }}