{{- if and .Values.storage.enabled .Values.storage.persistence.enabled (eq .Values.storage.storageType "local") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudscan.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudscan.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
{{- end }}