{{- if .Values.ui.enabled }}
{{- $_ := set . "serviceName" "ui" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudscan.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudscan.service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "cloudscan.service.selectorLabels" . | nindent 4 }}
{{- end }}